### ISSUE TITLE
Support network based multiple log import

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1084]
The existing log import api sends filenames between Brim & zqd, as it initially only needed to support the Brim setup where both are co-located. We should change the api to send log data over the socket, including supporting multiple logs in a single api call.

UPDATE- We want to include the new multipart-form upload but keep the old path based endpoint. The old path based endpoint is useful in that s3 logs can be posted directly to the server.

**Comment by philrz** [comment]
Verified in `zq` commit `9bcc81b5`.

To show the "before", back on `zq` commit `067eb47`, if we sniffed the traffic during a `zapi post` of multiple log files, we could see the local file paths being mentioned, which `zqd` would then access directly to perform the import. From a Wireshark sniff:

```
POST /space/sp_1kFA7czUliEJC92z0pnMsGPEHVn/log HTTP/1.1
Host: localhost:9999
User-Agent: zqd-client-golang
Content-Length: 190
Content-Type: application/json
Accept-Encoding: gzip

{"paths":["file:///Users/phil/work/zq-sample-data/zeek-default/smb_files.log.gz","file:///Users/phil/work/zq-sample-data/zeek-default/stats.log.gz"],"stop_err":false,"json_type_config":null}
```

This meant the client and `zqd` had to both have access to the same filesystem (i.e. typically running on the same host) in order for the import to work. In the example above, I was attempting to post from a `zapi` client on my laptop to a remote `zqd` that was running inside a VirtualBox VM. Therefore my client saw the following error due to `zqd` not being able to access a file at the provided path.

```
$ zapi -h localhost:9999 -s My_Test post -f smb_files.log.gz stats.log.gz
posting...
status code 404: file:///Users/phil/work/zq-sample-data/zeek-default/smb_files.log.gz
```

Now at `zq` commit `9bcc81b5`, sniffing in Wireshark we can see the file contents are now part of the `POST`.

```
POST /space/sp_1kFAiC0W65ft0bToEwprUxbA5os/log HTTP/1.1
Host: localhost:9999
User-Agent: zqd-client-golang
Transfer-Encoding: chunked
Content-Type: multipart/form-data; boundary=102ac892a3dd727bdda7e186ba3a9c366e38ad13d507f6b07cbc61c45eb1
Accept-Encoding: gzip

e4
--102ac892a3dd727bdda7e186ba3a9c366e38ad13d507f6b07cbc61c45eb1
Content-Disposition: form-data; name=""; filename="file:///Users/phil/work/zq-sample-data/zeek-default/smb_files.log.gz"
Content-Type: application/octet-stream


303
....v..]..smb_files.log...]o.0...._1)...a.....4e-.e*..!.414..,.P....|.l..u$...;...{...<,.2+>...r\......8....z4N.,..j.....j.s...yX..3....6...:..a.....jf.A...[.(
[more random bytes]

--102ac892a3dd727bdda7e186ba3a9c366e38ad13d507f6b07cbc61c45eb1
Content-Disposition: form-data; name=""; filename="file:///Users/phil/work/zq-sample-data/zeek-default/stats.log.gz"
Content-Type: application/octet-stream


269
....v..]..stats.log..T...0.<._Q...h
[more random bytes]
```

And the `zapi post` that failed before now works:

```
$ zapi -h localhost:9999 -s My_Test post -f smb_files.log.gz stats.log.gz
posted 1.39KB in 2.762279ms

$ zapi -h localhost:9999 -s My_Test get -t 'count() by _path'
#0:record[_path:string,count:uint64]
0:[stats;5;]
0:[smb_files;12;]
```

Thanks @mattnibs!
