### ISSUE TITLE
zqd: Add log ingest support for archive spaces

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1131]

**Comment by alfred-landrum** [comment]
We ran an into issue when discussing how to handle this in the "drag a pcap" import of Brim: the "long conn" problem of Zeek. That is: if you feed a pcap to the zeek runner, and occasionally take a snapshot of the zeek logs, you will occasionally see timestamps prior to a previous snapshot, since the timestamp for a zeek conn record is the connection start, but the record is emitted at connection end. (@mattnibs : please make sure I'm describing this accurately).

We want to feed snapshots of the transformed zeek logs into the archive, so that a Brim user can examine & query the available data without waiting for the entire pcap to be read. We can do that by taking a snapshot of the logs, converting them  to zng, then import the delta of records from the last snapshots zng file (so that we don't import duplicate records). The new records may have timestamps that overlap with existing imported data - which we don't yet handle. This led to the discussion & design in #1183 .
