### ISSUE TITLE
zqd: Better error messaging if space pcap file no longer exists

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1195]
If a users moves or deletes the pcap file for a space, this can set off a series of misleading error responses for zqd api response.

Cases:
- calls to list spaces (e.g. `zapi ls`) returns this error `couldn't fetch spaces: status code 404: /Users/nibs/Code/my pcap.pcap`. This should not return any error.
- calls to info (`zapi info myspace`) returns: `couldn't fetch spaces: status code 404: /Users/nibs/Code/my pcap.pcap`- I'm not quite sure how this case should be handled. Would be nice if it still returned info but also included a warning that the pcap file cannot be found.
- searches (`zapi -s myspace get`) returns: `couldn't fetch spaces: status code 404: /Users/nibs/Code/my pcap.pcap`- Not dependent on pcap should not return an error
- pcap searches presumably returns 404 as well. Perhaps this is ok, but probably this should be a 500 error message pcap cannot be found

**Comment by philrz** [comment]
Verified in Brim commit`08420a3` talking to `zqd` commit `f3d2a04`.

First, I'll revisit the repro. The most egregious manifestation of this problem was in the Brim app. In prior GA releases such as the one tagged `v0.15.1`, if a pcap was imported but then moved/renamed/deleted from its original location, the app was forgiving of this. For example, here I've imported "hello-scratch.pcapng" into Brim `v0.15.1` (talking to `zqd` GA tagged `v0.19.1`), quit the app, then deleted the file at the filesystem layer. When I relaunch the app, it starts up fine and lets me see the Space and I can query the events via ZQL as before. However, the Packets button would still activate, and when clicked, I would get a helpful error message at the bottom of the window that pointed to the problem.

![image](https://user-images.githubusercontent.com/5934157/91866592-89eb4b80-ec27-11ea-8d66-c6d122580519.png)

However, let's say a user had many Spaces imported and had been unaware that one of the pcaps was no longer at its original location (such as if they'd been tidying up their filesystem). Brim GA tagged `v0.16.0` has the problems described in this issue and in this regard is no longer forgiving, as it would hang upon receiving the 404 response on any single Space. The error is viewable in DevTools. Before taking this next screenshot, I've simply closed my `v0.15.1` app, upgraded to `v0.16.0`, and started the app. In this case the `zqd` Brim is talking to is GA tag `v0.20.0`.

![image](https://user-images.githubusercontent.com/5934157/91867500-90c68e00-ec28-11ea-8318-da8fb0248e18.png)

From this spot if I close the app yet again and upgrade to a release artifact based on Brim commit `08420a3` which talks to `zqd` commit `f3d2a04`, now it starts without complaint.

![image](https://user-images.githubusercontent.com/5934157/91867704-ca979480-ec28-11ea-801d-120b91dff9c0.png)

Another side-effect of the fix is that now the packets button is grayed out. Some hover text might help here (tracked in https://github.com/brimsec/brim/issues/981), but the current behavior makes sense given there's no pcap to extract from.

Regarding the other `zapi` cases described in the opening text, with this same release artifact we now see improvement:

```
$ zapi ls
hello-scratch.pcapng

$ zapi info hello-scratch.pcapng
hello-scratch.pcapng
  id:           sp_1gujnO3IiZpcVoLdNGUqtSkqDGl
  name:         hello-scratch.pcapng
  data_path:    file:///Users/phil/Library/Application%20Support/Brim/data/spaces/sp_1gujnO3IiZpcVoLdNGUqtSkqDGl
  storage_kind: filestore
  span:         2020-03-09T15:42:03Z+1h45m49.865915001s
  size:         3.03KB
  pcap_support: false
  pcap_size:    0B
  pcap_path:    
  parent_id:    

$ zapi -s hello-scratch.pcapng get "tail 1"
conn	2020-03-09T15:42:03.826851Z	CBKzui3MKB9oYj08p4	192.168.10.120	62576	104.123.204.164	443	tcp	-	0.000428	0	31	SF	-	-	0	^dfAFa	3	156	3	187	-	US	-	-	37.751	-97.822
```

If I restore the pcapng file in its original location, the `zapi info` now returns `pcap_support: true`.

```
$ zapi info hello-scratch.pcapng
hello-scratch.pcapng
  id:           sp_1gujnO3IiZpcVoLdNGUqtSkqDGl
  name:         hello-scratch.pcapng
  data_path:    file:///Users/phil/Library/Application%20Support/Brim/data/spaces/sp_1gujnO3IiZpcVoLdNGUqtSkqDGl
  storage_kind: filestore
  span:         2020-03-09T15:42:03Z+1h45m49.865915001s
  size:         3.03KB
  pcap_support: true
  pcap_size:    12.40KB
  pcap_path:    file:///Users/phil/pcap/hello-scratch.pcapng
  parent_id:    
```

Thanks @mattnibs!
