### ISSUE TITLE
Internal k8s service

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1208]
We plan to stand up an internal service using the recently added k8s configuration. This will give us experience operating, updating, and maintaining a Brim accessible, zqd based service. This is a placeholder issue that will convert to an epic as we refine requirements and tasks.

**Comment by marktwallace** [comment]
Here is some discussion of where we are and what the next phase should be.

A previous PR, #1173, completed a proof-of-concept and demonstration of K8s deployment of zqd. As of that PR, all the important moving parts for deployment were in place, along with setup instructions for test environments.

However, none of the typical tools for develoment, including and approach to CI/CD and testing, were included in #1173.

So, the next phase of work is to create a pattern for development and testing on K8s that is  convenient and easy to understand for the whole Brim development team.

I suggest that we use Tilt for dev, because it is a complete solution that does not have a steep learning curve. Currently I'm working in the tiltfile-for-k8s-dev branch and will create a PR for that branch when it is ready. At that point we should convert this issue into an epic and close the first subissue of the epic, which will provide a local development process and a Tiltfile.

There will be more subissues on the way to creating an internal service. We start with a K8s development environment so all of the Brim team can engage in thinking about how to move in concrete steps towards the goal.

**Comment by marktwallace** [comment]
I did not use Tilt. Instead, there are Makefile rules and other changes so each developer can create a separate namespace for development on the zq-test cluster in us-east-2.
