### ISSUE TITLE
resolve multi-type sets in zng spec and zq implementation

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1220]
On another topic triggered by working on zst, I would like to figure out what we do with sets.  They come from zeek and show up in the brim app, but we've only ever seen single-type sets and the spec currently says `<ntypes>` must be 1, in conflict with zeek's generality.  e.g., I think you could declare
set[string,int]
in zeek then say
1 in [["foo",2],["bar",1]] 
and this would be true (maybe).  Certainly you could say
["foo",2] in [["foo",2],["bar",1]] 

If we got rid of <ntype> from the set typedef spec, then we could by future-proofed by knowing if we really had to someday map a zeek multi-typed set, we could do so with a type alias

#zeek_mset0=set[record[c0:type0,c1:type1,...]]

and the app could even hide the dummy column names in the UI because it knows it's funky type alias.  And if you really put set[record[]] in the zng, then the UI could display as is.  I'm guessing this will never need to be done so I like this approach.  Specfically, the proposal is to simplify the set typedef encodinig by getting rid of the <nytpes>  field... 

https://github.com/brimsec/zq/blob/zst/zng/docs/spec.md#3113-set-typedef

**Comment by philrz** [comment]
There was no user-facing change in functionality here. The [prior `set` typedef in the ZNG spec](https://github.com/brimsec/zq/blob/v0.22.0/zng/docs/spec.md#3113-set-typedef) had the concept of `ntypes` (number of types, i.e. so each element of the set could be a tuple, where each tuple is made up of multiple typed values) but also specified that it could only be equal to `1`. To be in sync with this, `zq` populated `ntypes` with `1` when creating sets and checked it to be `1` when reading them, but this all effectively added up to only supporting single-typed sets. With the change in the linked PR, `ntypes` for sets has been dropped from the ZNG spec and `zq` entirely, locking in support for only single-typed sets. Therefore if a user wants to create a set where each element contains multiple values, they'd just need to define that using one of the existing multi-value types (set, array, record, union) and hence have "a set of sets", "a set of arrays", etc.

The closing comments in the issue description above still apply in that the current building blocks (such as aliasing) _could_ allow us to one day support multi-type sets (i.e. sets of tuples) without further changes to the ZNG spec. However, we don't anticipate this will be necessary because Zeek is the only system we're aware of that has them, and even then it's only inside their "script" land. The last time we tested it, Zeek's own logger has no way to output them when multi-typed.
