### ISSUE TITLE
add bytes type

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1315]
Add bytes type to zq. Allow index operator that works on arrays to apply to the bytes type and return a byte value of the result.

**Comment by mccanne** [comment]
Add bytes type to zq.  Allow index operator that works on arrays to apply to the bytes type and return a byte value of the result.

**Comment by philrz** [comment]
Verified in `zq` commit `18045ab`.

The `bytes` type can now be read/written using `zq`. Since it represents a sequence of bytes encoded as base64, there's also Base64 helper functions to help get these in & out of strings.

Example:

```
$ echo -n 'hello' | base64
aGVsbG8=

$ cat bytes.tzng 
#0:record[encoded_greeting:bytes]
0:[aGVsbG8=;]

$ zq -t 'put greeting_as_string=encoded_greeting:string | put b64_in_string=toBase64(greeting_as_string) | put b64_in_bytes=toBase64(greeting_as_string):bytes | put another_decoded=fromBase64(b64_in_string):string' bytes.tzng 
#0:record[encoded_greeting:bytes,greeting_as_string:string,b64_in_string:string,b64_in_bytes:bytes,another_decoded:string]
0:[aGVsbG8=;hello;aGVsbG8=;YUdWc2JHOD0=;hello;]
```

As for this part of the opening description:

>Allow index operator that works on arrays to apply to the bytes type and return a byte value of the result.

This has yet to be done and is tracked in #1421.

Thanks @mccanne!
