### ISSUE TITLE
Restore text representation before printing as CSV

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1326]
Repro is with `zq` commit `2fe0e93`.

There seem to be several minor variations in the world when it comes to formatting CSV output. However, short of adhering to any one true spec, we're currently letting through some changed values that likely don't belong there. Here I'm starting my data as NDJSON and comparing our output with the top Google hit for "json to csv" (https://www.convertcsv.com/json-to-csv.htm).

Backslashes:

```
$ echo '{"BackSlash":"\\"}' | zq -f csv -
BackSlash
\\
```

The JSON-to-CSV tool gives:

```
BackSlash
\
```

A lone hyphen (maybe will be fixed by #1325?)

```
$ echo '{"Hyphen":"-"}' | zq -f csv -
Hyphen
\u002d
```

The JSON-to-CSV tool gives:

```
Hyphen
-
```

A null value:

```
$ echo '{"a": "a", "nothing":null, "z": "z"}' | zq -f csv -
a,nothing,z
a,-,z
```

The JSON-to-CSV tool gives:

```
a,nothing,z
a,,z
```

Overall I get the impression that we just need to undo some of our escaping and handling of special characters before doing the final output as CSV. I discussed this with @mccanne and he summarized:

> I'm using the same logic as the text output so we need to fix this. I don't know that we have the correct methods on the zng types to just print a text representation without the escape business.

**Comment by nwt** [comment]
We currently escape backslashes to distinguish them from the \xhh escape sequence we use to represent bytes that don't fit within the current character encoding (i.e., non-ASCII bytes for `zq -U=false`, and bytes that aren't part of a valid UTF-8 sequence for `zq -U=true`.

Here are some options that would let us stop escaping backslashes.
1. 
1. Escape them only in strings that contain \xhh sequences.


We could simply stop escaping backslashes for CSV output, but that renders any \xhh sequence ambiguous

One way we could stop escaping backslashes is to replace the boolean -U flag with a -charset flag that could be set to ascii (does what -U=false does now), utf8 (does what -U=true does now), or none (no escaping ever).

**Comment by nwt** [comment]
We escape backslashes to distinguish them from the `\xhh` escape sequences we use to represent bytes that don't fit within the current character encoding (i.e., non-ASCII bytes for `zq -U=false`, and bytes that aren't part of a valid UTF-8 sequence for `zq -U=true`, but we've got options if we want to limit or avoid this for CSV.

1. Never escape backslashes, but continue escaping bytes outside the current encoding. This seems ill-advised since it renders `\xhh` sequences ambiguous (i.e., `\x00` could be `[]byte{'\\', 'x', '0', '0'}` or `[]byte{0}`).
1. Escape backslashes only to indicate they aren't part of a `\xhh` sequence (so `\` is `[]byte{'\\'}`; `\x0g` is `[]byte{'\\', 'x', '0', 'g'}`; `\x0f` is `[]byte{15}`; and `\\x0f` is `[]byte{'\\', 'x', '0', 'f'}`).
1. Replace the `-U` flag with a `-charset` flag that could be set to `ascii` (does what `-U=false` does now), `utf8` (does what `-U=true` does now), or `none` (don't backslash-escape anything).
1. Don't backslash-escape anything. (The `-U` flag would then cease to apply to `-f csv`.)

I of course like option 4 (don't backslash-escape anything) because it's the simplest.

**Comment by philrz** [comment]
Verified in `zq` commit `f776da2a`. Revisiting the examples from the opening issue description:

Backslashes:

```
$ echo '{"BackSlash":"\\"}' | zq -f csv -
BackSlash
\
```

A lone hyphen:

```
$ echo '{"Hyphen":"-"}' | zq -f csv -
Hyphen
-
```

A null value:

```
$ echo '{"a": "a", "nothing":null, "z": "z"}' | zq -f csv -
a,nothing,z
a,,z
```

Looks perfect. Thanks @nwt!
