### ISSUE TITLE
brim/zqd handling for breaking zng changes

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1376]
Some of the zng changes will be backwards incompatible, so the new zq code won't be able to handle older zng files. For the next release of Brim/zqd, we can bundle the v0.22.0 version of `zq` (before the zng changes) and have a space migration that  uses it to read the old zng data, pipe it out as tzng, and then have the tzng written with the new zng code.

**Comment by alfred-landrum** [comment]
@mccanne is adding a reader for the older zng files here:
https://github.com/brimsec/zq/pull/1386

I'll work on the space migration code that will use that work to perform the translation & rewrite.

**Comment by philrz** [comment]
#1414 shows some numbers regarding the performance delta.

**Comment by alfred-landrum** [comment]
Closing; final zqd migration work is in #1574 and #1576 .

**Comment by philrz** [comment]
Verified in Brim commit `a1ec202` talking to `zqd` commit `d3bfd3e`.

To verify, as shown in the attached video, I started by running Brim GA tagged `v0.18.0` and imported data into two Spaces, resulting in one with an `all.zng` about 74 MB in size and the other `all.zng` about 80 MB in size.

```
~/Library/Application Support/Brim/data$ tree -s spaces/
spaces/
├── [        160]  sp_1k3pJJ4jDoaNuC7nxDM7q8gUobm
│   ├── [   80045532]  all.zng
│   ├── [        194]  config.json
│   └── [         92]  info.json
└── [        192]  sp_1k3pK7HSm6el6ydww4EqBEwUWk8
    ├── [   74348557]  all.zng
    ├── [        190]  config.json
    ├── [         92]  info.json
    └── [     573388]  pcap.json

2 directories, 7 files
```

I then closed the app and upgraded to a release artifact based on Brim commit `a1ec202` that includes `zqd` commit `d3bfd3e`. The migration on both Spaces begins immediately once the app launches, and the progress is captured in the `zqd.core` log.

```
...
{"level":"info","ts":1604939787.489334,"msg":"Alpha zng migration start","space_id":"sp_1k3pJJ4jDoaNuC7nxDM7q8gUobm","file":"/Users/phil/Library/Application Support/Brim/data/spaces/sp_1k3pJJ4jDoaNuC7nxDM7q8gUobm/all.zng"}
{"level":"info","ts":1604939787.5074492,"msg":"Alpha zng migration start","space_id":"sp_1k3pK7HSm6el6ydww4EqBEwUWk8","file":"/Users/phil/Library/Application Support/Brim/data/spaces/sp_1k3pK7HSm6el6ydww4EqBEwUWk8/all.zng"}
...
```

The app is in no way "blocked" during this migration, as I'm free to click tabs and import data to new Spaces. If I click to access one of the Spaces still in the middle of import, I see a "spinner", similar to if I'd executed a query that was taking a while to execute.

As shown in the video, once the first Space finishes migration, its events and the histogram are immediately displayed. I then click to the other Space and a few seconds later that one gets filled in as well. The messages in the log show as each migrations finishes.

```
...
{"level":"info","ts":1604939862.983514,"msg":"Alpha zng migration success","space_id":"sp_1k3pK7HSm6el6ydww4EqBEwUWk8","file":"/Users/phil/Library/Application Support/Brim/data/spaces/sp_1k3pK7HSm6el6ydww4EqBEwUWk8/all.zng"}
{"level":"info","ts":1604939873.168811,"msg":"Alpha zng migration success","space_id":"sp_1k3pJJ4jDoaNuC7nxDM7q8gUobm","file":"/Users/phil/Library/Application Support/Brim/data/spaces/sp_1k3pJJ4jDoaNuC7nxDM7q8gUobm/all.zng"}
...
```

The total time from the start of the first migration was just over 85 seconds, for an effective throughput of about 1.89 mbyte/sec. Of course, this result will vary in other environments based on CPU speed as well as number of Spaces, since these conversions are happening in parallel and take advantage of multiple cores.

[Verify.mp4.zip](https://github.com/brimsec/zq/files/5511979/Verify.mp4.zip)

I also separately verified (not captured in video) that if I quit the app after one Space has finished migrating but the other has not, when I relaunch the app, it begins the migration process for the ones that are still in alpha format, though I'm free to start using the ones that already completed migration.

Thanks @alfred-landrum!
