### ISSUE TITLE
ndjson: option to omit missing values 

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#1381]
The typed ndjson reader currently fills in `nil` for any field that is absent in an incoming record. This guarantees that once a descriptor has been identified for a record (based for example on a `_path`-based matching rule), the record will conform to that descriptor. 

However, in some cases, one might want to define a sort of "uber-descriptor" in `types.json`. In that case, rather than have `nils`, it would be nicer to have the typed reader create record types that omit the nil fields altogether. This behavior should be a configurable option.

**Comment by philrz** [comment]
@henridf and I talked about this one offline.

This one is linked to the Suricata work because some parts of the `alert` object in `eve.json` (e.g. the `metadata` fields) can be quite different depending on top-level characteristics of the alert (e.g. the `category`). This is a little different from what we're accustomed to in Zeek where the event for every `_path` truly begins life in Zeek land as part of a single wide schema with fields that may be present/absent. Therefore @henridf's concern was that our attempts to capture all the alert permutations under a single/wide descriptor would produce named fields present-&-set-to-`null` for some alert categories that normally never include those fields in their `eve.json` representation. By omitting those fields, the data in ZNG would be a closer/minimal match to how they typically look in `eve.json`.

OTOH, my concern after thinking this through is that it would create a diverse set of descriptors for the alerts stream, and what this would mean all the way up to the Brim UX. For example, right now for column headers to appear automatically in Brim, all the data has to fit under a single descriptor. This has led me to instinctively notice & think through situations where extra descriptors might get created for data that could have fit under a single schema.

At the close of the chat it still wasn't clear which approach is the right one for our Suricata plans. However, we settled on a plan that we'll start with the current behavior that represents the alert stream within a single descriptor, then depending on how that looks & feels up through the app layer, we'll revisit this one.

**Comment by philrz** [comment]
As the MVP of Suricata is drawing to a close, @henridf and I discussed this one again and agreed that the topic described here should now be considered in the wider context of the "generic ingest" project. I'm hanging it off the Epic for that project as a reminder that we consider how it fits into the designs/implementation we decide on.

**Comment by henridf** [comment]
This will be supported with the new shaping functions by doing cast+order+crop (no fill). 

(This is the dual of https://github.com/brimsec/zq/issues/1358#issuecomment-762680417)
