### ISSUE TITLE
create initial join proc

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#1629]

**Comment by philrz** [comment]
Verified in `zq` commit `d35b16a1`. The linked PR has even more detail, but here's a quick summary of what's working at the moment, with details subject to change.

Typical security use cases for the `join` processor will likely involve threat intel feeds, though here's a simple example that uses the self-contained [zq-sample-data](https://github.com/brimsec/zq-sample-data). Let's say we're mindful of the fact that SMB mappings are often long-lived, and we know the Zeek `conn` log contains a `duration` field that says how long a connection was observed to remain open. Therefore we can join on the `uid` field that's present in both logs to add an additional field `connect_time` to our Zeek `smb_mapping` events that contains the `duration` value from the corresponding `conn` event.

```
$ zq -P -f table '(sort uid ; sort uid) | join uid=uid connect_time=duration' smb_mapping.log.gz conn.log.gz
_PATH       TS                          UID                ID.ORIG_H     ID.ORIG_P ID.RESP_H    ID.RESP_P PATH                     SERVICE NATIVE_FILE_SYSTEM SHARE_TYPE CONNECT_TIME
smb_mapping 2018-03-24T17:15:53.264234Z C07evA1GPFHxSDnAR4 10.164.94.120 45303     10.47.24.170 445       \\\\PARKINGGARAGE\\IPC$  -       -                  PIPE       0.104151
smb_mapping 2018-03-24T17:16:27.781406Z C0X8T81PLwbbW6pqta 10.164.94.120 32965     10.47.24.170 445       \\\\PARKINGGARAGE\\IPC$  -       -                  PIPE       0.072151
smb_mapping 2018-03-24T17:16:27.486227Z C0ehcH1Xrs5txrIvl9 10.164.94.120 35911     10.47.3.218  445       \\\\SMARTIES\\IPC$       -       -                  PIPE       0.089105
...
```

Things to note about this command line:

* The `-P` flag in zq is used to specify the multiple inputs. As described in #1616, the number of inputs on the command line must match the number of inputs in the ZQL, and at most one of the inputs on the command line can be `-` to read from stdin.

```
$ zq -P -f table '(sort uid ; sort uid) | join uid=uid connect_time=duration' smb_mapping.log.gz conn.log.gz stats.log.gz 
number of input sources must match number of parallel inputs in zql query

$ cat conn.log.gz | zq -P -f table '(sort uid ; sort uid) | join uid=uid connect_time=duration' smb_mapping.log.gz -
_PATH       TS                          UID                ID.ORIG_H     ID.ORIG_P ID.RESP_H    ID.RESP_P PATH                     SERVICE NATIVE_FILE_SYSTEM SHARE_TYPE CONNECT_TIME
smb_mapping 2018-03-24T17:15:53.264234Z C07evA1GPFHxSDnAR4 10.164.94.120 45303     10.47.24.170 445       \\\\PARKINGGARAGE\\IPC$  -       -                  PIPE       0.104151
smb_mapping 2018-03-24T17:16:27.781406Z C0X8T81PLwbbW6pqta 10.164.94.120 32965     10.47.24.170 445       \\\\PARKINGGARAGE\\IPC$  -       -                  PIPE       0.072151
smb_mapping 2018-03-24T17:16:27.486227Z C0ehcH1Xrs5txrIvl9 10.164.94.120 35911     10.47.3.218  445       \\\\SMARTIES\\IPC$       -       -                  PIPE       0.089105
...
```

* The inputs need to be sorted by the key fields on which you intend to join, otherwise the output is undefined. If you've pre-sorted your inputs, you could put `filter *` in place of `sort <fieldname>` at the beginning of the ZQL.

* The basic summary syntax is:

```
... | join left-key-expr = right-key-expr cut1,cut2,...
```

* The "cuts" are the same syntax as [`cut` processor](https://github.com/brimsec/zq/tree/master/zql/docs/processors#cut) field expressions and add values from the right record into the left record.  If there is a field name collision, the name will be given a suffix of _2, _3, etc.

* The key expressions are like [`sort` processor](https://github.com/brimsec/zq/tree/master/zql/docs/processors#sort) expressions.

* There is currently no attempt to put explicit null values in the columns for missing righthand keys. If this is desired, a [`fuse` processor](https://github.com/brimsec/zq/tree/master/zql/docs/processors#fuse) at the end of the ZQL will add these. For example, we know not all connections observed by Zeek generate `weird` events. Making a simple attempt to `join` the `conn` events with the `name` values from corresponding `weird` events where they exist, this ends up creating separate record definitions for the connections that have `weird` events and the ones that don't, as can be seen in the TZNG output.

```
$ zq -P -t '(sort uid ; sort uid) | join uid=uid weird_name=name' conn.log.gz weird.log.gz
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring]]
0:[conn;1521912734.500897;C0002i1FTbwDjYiDo5;[10.218.221.240;8;10.47.7.54;0;]icmp;-;1.298196;0;0;OTH;-;-;0;-;4;112;0;0;-;]
0:[conn;1521912672.426813;C000NXHP3tORDvjT8;[10.174.251.215;56656;10.47.2.20;49154;]tcp;-;0.000002;0;0;S0;-;-;0;S;2;88;0;0;-;]
...
#1:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring],weird_name:bstring]
1:[conn;1521911950.310534;C00YVg313nPS4nDC9a;[10.128.0.241;55348;10.47.1.208;80;]tcp;-;0.001225;250;0;RSTR;-;-;0;ShADTr;6;828;4;200;-;bad_HTTP_request;]
1:[conn;1521911950.310534;C00YVg313nPS4nDC9a;[10.128.0.241;55348;10.47.1.208;80;]tcp;-;0.001225;250;0;RSTR;-;-;0;ShADTr;6;828;4;200;-;line_terminated_with_single_CR;]
...
```

However, if we add `fuse`, we get a single record definition with the null values filled in.

```
$ zq -P -t '(sort uid ; sort uid) | join uid=uid weird_name=name | fuse' conn.log.gz weird.log.gz
#port=uint16
#zenum=string
#0:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],proto:zenum,service:bstring,duration:duration,orig_bytes:uint64,resp_bytes:uint64,conn_state:bstring,local_orig:bool,local_resp:bool,missed_bytes:uint64,history:bstring,orig_pkts:uint64,orig_ip_bytes:uint64,resp_pkts:uint64,resp_ip_bytes:uint64,tunnel_parents:set[bstring],weird_name:bstring]
0:[conn;1521912734.500897;C0002i1FTbwDjYiDo5;[10.218.221.240;8;10.47.7.54;0;]icmp;-;1.298196;0;0;OTH;-;-;0;-;4;112;0;0;-;-;]
0:[conn;1521912672.426813;C000NXHP3tORDvjT8;[10.174.251.215;56656;10.47.2.20;49154;]tcp;-;0.000002;0;0;S0;-;-;0;S;2;88;0;0;-;-;]
...
```

Thanks @mccanne!
