### ISSUE TITLE
"malformed zng record" while running large aggregation

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#1803]
Repro is with `zq` commit `d62f4b1b` and the attached test file:

[repro.zng.gz](https://github.com/brimsec/zq/files/5682298/repro.zng.gz)

```
$ zq 'collect(name) by value' repro.zng.gz > /dev/null
malformed zng record
```

The original repro was actually involving the much larger (23 GB) public data set at https://opendata.rapid7.com/sonar.fdns_v2/2020-11-27-1606435855-fdns_a.json.gz. However, I've narrowed it down to just what's in the attachment above.

For whatever reason, what's in the attachment is the magic amount. If I trim either the top or bottom record from the file, it doesn't repro. So something is making it tip over at that point.

```
$ zq -t 'count()' repro.zng.gz 
#0:record[count:uint64]
0:[1650832;]

$ zq 'head 1650831 | collect(name) by value' repro.zng.gz > /dev/null
[no error]

$ zq 'tail 1650831 | collect(name) by value' repro.zng.gz > /dev/null
[no error]
```

**Comment by mccanne** [comment]
Here's the culprit..

https://github.com/brimsec/zq/blob/d62f4b1b65d17be7129808aa858868da682328dc/zio/zngio/reader.go#L190

The collect aggregation makes records in size that exceed the read buffer max and this error here is poor feedback for this condition.   It happens in this case when a large row gets written to the spill file then exceeds the buffer limit on readback/merge. 

A few thoughts...

* we should give a reasonable message about a data value's size exceeding the buffer size (with the actual sizes in the error message)
* we should have a flag to override the default readbuffer limit of 10MB
* we should catch "big rows" at the aggregation outputs and report them to the user before they ever get written to storage (or spilled to disk for ext mergesort); this is relevant wrt to brim talking to a cloud service compared to running zq on your laptop.
* we should explore other convenient zql mechanisms that solve the union()/collect() workloads when you know you otherwise have very large rows.  they are super convenient as is but there is a not-too-big row workflow and use case and then a batch processing join/distributed-sort type of workflow and each should be easy to move between these two contexts.

**Comment by mccanne** [comment]
Net net, it isn't a corrupt data problem but is a simple buffer overflow issue that was caught but reported with a confusing error message...

**Comment by philrz** [comment]
I've verified with the original repro that we've achieved the goal of improving the error message. As of `zq` commit `1e501e85`:

```
$ zq -version
Version: v0.26.0-25-g1e501e85

$ zq 'collect(name) by value' repro.zng.gz > /dev/null
large value of 10485775 bytes exceeds maximum read buffer (10485760 bytes)
```

For the wider issue of providing the user a way to successfully read and query this data despite its challenging nature, a few open issues remain that contribute to this:

* https://github.com/brimsec/zq/issues/1494
* https://github.com/brimsec/zq/issues/1807
* https://github.com/brimsec/zq/issues/1813
