### ISSUE TITLE
AWS Aurora instance for zqd-test cluster

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#1874]
As part of #1718 , we'll be able to either spin up an on-demand Postgresql instance with the helm chart, or use endpoints to an existing database instance. For our zqd-test cluster, we want to use an AWS Aurora instance, as that's our intent for eventual production service.

**Comment by marktwallace** [comment]
There are three phases to getting this working:
(1) Modify the Helm charts so Postgres is an optional dependency. This is working now. It turned out to be a significant restructuring, since the "tags" mechanism for managing dependencies in Helm only seems to work correctly for two layer of dependencies, and previously to this issue our Helm chart had three layers. We flattened the structure so the tags work as intended.
(2) Aurora needs to be installed in a VPC. Installing Aurora directly into the VPC for our EKS cluster had some drawbacks because it was hard to configure and trouble-shoot, and it would make it awkward to reconfigure our use of EKS without also disrupting our database, when we would prefer to two be independently maintained. Instead, we setup up Aurora in its own VPC with a peering connection to the EKS VPC. It was not easy to get this right -- the documentation was incomplete and most examples has flaws. Trouble-shooting route tables, subnets, and security groups is slow. We developed a shell script to make it this a reproducible procedure for when we need it for a production install. Note that these procedures are high-level and include steps that cannot be done with CloudFormation. Also note that the procedures should not be repeated in our test account, since we will run out of free VPC's if we do.
(3) Modify and verify that the automated EKS deployment tests work both with and without Aurora. This is the step I'm on right now.

**Comment by marktwallace** [comment]
In order to do (3) above, we needed some way to manage users for the Aurora DB. Right now, for tests, all our code assumes the same Postgres user. For Aurora, all developers will share the same Aurora cluster so we all need to have separate user names. I added procedures and scripts to create Postgres users and K8s secrets for Postgres creds for each namespace. We will have a unique Aurora Postgres user for each K8s namespace, so we will have good test isolation for multiple test environments but they can all share the same EKS cluster and the same Aurora cluster.

Next on the list is revising Matt's migration code to handle different Postgres users. I am hoping this is just changes to the init containers in the K8s config, but there may be other changes too.

**Comment by marktwallace** [comment]
The multi-phase project is done!

I added notes to the PR, but I am repeating them here for good measure:

(1) An Aurora cluster has been created. The instructions in aurora.md can be used to reproduce the configuration, but this only needs to be done one per AWS account, so we should not do it again until we start a Prod account.

(2) The Aurora cluster was created in a separate VPC from EKS. This will allow us to reconfigure EKS or create additional clusters without needing to change our Aurora cluster. We set up VPC peering from the EKS VPC to the Aurora VPC. Peering is a tricky to test and time-consuming setup process, so we created a script (peering.sh) so the key steps can be reproduced when we need to do it again for our Prod cluster. As per best practices for security, the Aurora cluster is not publicly accessible. It can only be accessed from within our EKS cluster.

(3) The Helm K8s deployment scripts needed to be restructured to allow Postgres (and Redis) to be optional containers. We use Helm "tags" for the optional features.

(4) Makefile targets needed to be adjusted and a new target created for deployments that use Aurora.

(5) All development and test activities will share a single Aurora cluster. Like EKS, Aurora can become very expensive if each developer needs their own cluster, so we developed a set of conventions to share the Aurora cluster that corresponded to the way we share the EKS test cluster. Each developer or test environment will use a separate Aurora database within the cluster. This provides ideal isolation for testing, which is a good match for the namespace isolation we use in our EKS cluster. There are instructions in aurora.md for how to create Aurora test users and databases using kubectl and psql. It is a manual process, and I will be happy to do it for developers that do not want to deep dive into kubectl and psql.

(6) The cd.yaml tests have been updated to add tests for Aurora. The master deploy now runs on Aurora, which means that environment will be stateful and use db migrations to maintain consistent state as we develop. The master deploy now runs the same tests we run in the test namespace, but runs them with a migrated Aurora db rather than a new, empty database. As we add more tests, the tests for master may diverge from the smoke tests that run in a temporary namespace, because of the need to support migrations.
