### ISSUE TITLE
zqd archive error: metadata for file not found

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#1960]
This test failure was seen on the `eks-test-zapi-1`ci  job for the postgres helm pr: https://github.com/brimsec/zq/pull/1948

Given that zqd successfully connects with postgres, this appears unrelated to the feature work in the pr.

Test Logs:

```
zapi -s files get -workers 2 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
0:[files;1521940131.094903;FgzbkQ15TOoOENn1lb;[198.199.95.203;][10.47.25.80;][Cc4q8L1Hhp9MjJiVcl;]SSL;0;[MD5;SHA1;X509;SHA256;]application/x-x509-ca-cert;-;0;-;F;1174;-;0;0;F;-;b15409274f54ad8f023d3b85a5ecec5d;e6a3b45b062d509b3382282d196efe97d5956ccb;25847d668eb4f04fdd40b12b6b0740c567da7d024308eb6c2c96fe41d9de218d;-;-;-;]
Handling connection for 9867
status code 400: invalid worker op request: failed to read chunk metadata from s3://zq-ci-test/21-01-12.342/zd/20180323/m-1myPUtlCc6vWqxJBlJKTA2qRfEy.zng: item does not exist
```

Action url: https://github.com/brimsec/zq/pull/1948/checks?check_run_id=1688778486

**Comment by mattnibs** [comment]
My working hypothesis is that this comes from an issue with compaction/purge. The first step will probably be to add some logging around compaction and purge and also ensure that the `eks-test-zapi-1` ci job stashes these logs somewhere accessible.

**Comment by mattnibs** [comment]
Another failure on master: https://github.com/brimsec/zq/runs/1689722582?check_suite_focus=true

**Comment by marktwallace** [comment]
When this issue is closed, we should create a new issue to fix the architectural problem.

In order to fix this, we will have to avoid relying on S3 dir operations for reading archives. We should make all the information for reading an archive available in Postgres.

I suspect the problem is that S3's constancy model is not atomic with respect to directories. Here a are two relevant quotes from the most recent S3 docs (after their announcement about consistency):

"S3 also provides strong consistency for list operations, so after a write, you can immediately perform a listing of the objects in a bucket with any changes reflected."

"Updates to a single key are atomic."

The second quote implies that the converse is NOT true -- if we update multiple objects (possibly in different threads of execution) and then do an S3 dir operation, we may not see a complete list.

This leads to the conclusion that we should keep track of our own S3 keys, and use S3 dir only for disaster recovery.

**Comment by alfred-landrum** [comment]
I had filed #1985 to track a longer term solution.

I don't think that interpretation of the S3 consistency (including the
recent announcement on strong consistency) is quite right, but it doesn't
make a difference to our current code: We don't update S3 keys, we only add
or delete them, and we don't rely on operations that involve creating
multiple keys to be seen atomically. For example, we handle the case where
we see a chunk file but don't see it's metadata file, as that's the order
the chunk writer uses when it adds new chunks to an archive.
