### ISSUE TITLE
Migrate zeek typed json to Z

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#2104]
(This is the Zeek equivalent of #1871 .)

**Comment by philrz** [comment]
Note to self: When this exists, we can verify by repeating an exercise we'd done with the old typing system:

- Start with TSV and NDJSON representations of logs that both came out of the same Zeek run ([zq-sample-data](https://github.com/brimsec/zq-sample-data) can cover this)
- Import each into separate Spaces
- Output what's in each Space in one of our text formats
- `diff` the outputs and see how close they are

In the past this has revealed some subtle differences, but we can make sure they're all cosmetic or otherwise acceptable.

**Comment by philrz** [comment]
In the time since this issue was addressed, I ended up making an additional improvement to the shaper config via #2368 and then verified that new config in those PR notes so we'd know it was ok to merge. Now that it's merged I think we're all set to start using shaping instead of the legacy `types.json` approach for importing Zeek NDJSON into the Brim app.
