### ISSUE TITLE
switch default

### ISSUE THREAD

**Issue by mccanne** [brimsec/zq#2322]
Switch should use the keyword "default" to easily refer to the default case if nothing matches.

It shouldn't have to appear at the end but should behave as it does.

**Comment by philrz** [comment]
Verified in `zq` commit 7ee2a8d.

Here's an example based on a use case for which I originally was seeking this feature. Back before we had the fix to #962, we had to use the `iso()` functions to turn ISO timestamps into `time` type fields. When I first sat down to verify #2104, the Z script at that time was only doing this conversion via `iso()` for the `ts` and `_write_ts` fields that are on 100% of the Zeek NDJSON events. However, this left out a bunch of other Zeek fields that we'd have wanted to cast to the `time` type.

To achieve this, with the functionality added in the linked PR, I can use an alternate Z shaper script ([shaper-zq-2322.zql.gz](https://github.com/brimsec/zq/files/6166783/shaper-zq-2322.zql.gz)) that uses an extra `switch` earlier in the pipeline to target those other time fields. Specifically:

```
...
put .=unflatten(.)
   | put ts=iso(ts), _write_ts=iso(_write_ts)
   | switch (
    case _path=dhcp => put lease_time=iso(lease_time)
    case _path=kerberos => put from=iso(from), till=iso(till)
    case _path=ntp => put ref_time=iso(ref_time), org_time=iso(org_time), rec_time=iso(rec_time), xmt_time=iso(xmt_time)
    case _path=pe => put compile_ts=iso(compile_ts)
    case _path=smb_files => put times.modified=iso(times.modified), times.accessed=iso(times.accessed), times.created=iso(times.created), times.changed=iso(times.changed)
    case _path=snmp => put up_since=iso(up_since)
    case _path=x509 => put certificate.not_valid_before=iso(certificate.not_valid_before), certificate.not_valid_after=iso(certificate.not_valid_after)
    default => *
   )
   | switch (
    case _path=files => put . = shape(files)
    case _path=http => put . = shape(http)
...
```

The `default` was necessary to let through all the other Zeek events that lacked the `time` fields.

Putting it to the test, I can shape using this script alongside the one that's committed to `zq` commit 7ee2a8d.

```
zq-sample-data/zeek-ndjson$ zq -Z -I shaper-zq-2322.zql '| sort -r ts,_path' *.gz > /tmp/isoshaper.zson
zq-sample-data/zeek-ndjson$ zq -Z -I shaper.zql '| sort -r ts,_path' *.gz > /tmp/mastershaper.zson
zq-sample-data/zeek-ndjson$ $ ls -l /tmp/*shaper.zson
-rw-r--r--  1 phil  wheel  944475435 Mar 18 12:30 /tmp/isoshaper.zson
-rw-r--r--  1 phil  wheel  944475435 Mar 18 12:31 /tmp/mastershaper.zson
zq-sample-data/zeek-ndjson$ diff /tmp/isoshaper.zson /tmp/mastershaper.zson
[no output]
```

Of course, this `iso()` treatment is now unnecessary because the enhancement from #962 allows the cast from ISO timestamp to `time` type to happen as part of shaping, which greatly simplifies the config. But surely this `default` option will come in handy in plenty of other future contexts.

Thanks @mccanne!
