### ISSUE TITLE
Consider a new zql operator for string pattern matching

### ISSUE THREAD

**Issue by aswan** [brimsec/zq#534]
Pattern matching of strings is currently written as `field = /pattern/`.
We should introduce a new operator for this, something like `field =~ /pattern/`.  In this way, we can also make glob matching explict: `name = *.html` would match the literal string `*.html` while `name =~ *.html` would do a glob.

**Comment by aswan** [comment]
#620 will get us most of the way there, there's a bigger issue with using regexps inside expressions, but issue #619 covers that larger issue.

**Comment by aswan** [comment]
Closing this, we still have the loose end from #619 but the operator described here is in place.

**Comment by philrz** [comment]
Verified in `zq` commit `d4cba02`.

There's a lot more permutations in the PR #620, but here's the basics. Start with the following data:

```
$ zq -t 'method=TRACE OR method=CONNECT | cut method' http.log 
#0:record[method:bstring]
0:[CONNECT;]
0:[TRACE;]
0:[TRACE;]
0:[CONNECT;]
```

We can use the `=~` operator in an expression to populate a new field with a boolean based on what's in a different field.

```
$ zq -t 'method=TRACE OR method=CONNECT | cut method | put isTrace = method=~"TRACE"' http.log
#0:record[method:bstring,isTrace:bool]
0:[CONNECT;F;]
0:[TRACE;T;]
0:[TRACE;T;]
0:[CONNECT;F;]
```

It also works with a glob wildcard.
```
$ zq -t 'method=TRACE OR method=CONNECT | cut method | put isTrace = method=~"*RAC*"' http.log
#0:record[method:bstring,isTrace:bool]
0:[CONNECT;F;]
0:[TRACE;T;]
0:[TRACE;T;]
0:[CONNECT;F;]
```

As @aswan pointed about above, this isn't possible yet with regexps, and #619 is tracking that.

While verifying this I was also reminded that bare references in such expressions resolve to the contents of the named field. Hence the `field is not present` warning in the following:

```
$ zq -t 'method=TRACE OR method=CONNECT | cut method | put isTrace = method=~TRACE' http.log
field is not present
#0:record[method:bstring]
0:[CONNECT;]
0:[TRACE;]
0:[TRACE;]
0:[CONNECT;]
```

Though the following variation works, since we populate a field called `TRACE` with a value we can compare to.

```
$ zq -t 'method=TRACE OR method=CONNECT | cut method | put TRACE="CONNECT" | put isTrace = method=~TRACE' http.log
#0:record[method:bstring,TRACE:string,isTrace:bool]
0:[CONNECT;CONNECT;T;]
0:[TRACE;CONNECT;F;]
0:[TRACE;CONNECT;F;]
0:[CONNECT;CONNECT;T;]
```

Thanks @aswan!
