### ISSUE TITLE
pcap SearchReader: Fix empty section headers

### ISSUE THREAD

**Issue by mattnibs** [brimsec/zq#563]
Currently the pcap.SearchReader will every section header it finds when reading through a pcap file. Instead the SearchReader should only write the headers that are needed in order to generate a valid pcap file from the search result. This especially means that calls to SearchReader.Read on "no results searches" should get an io.EOF on the first call. 

Additionally when creating a SearchReader, the reader should scan the pcap file it will search to ensure that packets capture data will be returned. If the reader finds the pcap file does not have any packets that match the search, NewSearchReader should return an error.

**Comment by philrz** [comment]
It sounds like the fix for this may also address a symptom we've run into where the output for a flow-not-found look like old-fashioned line noise. This was originally cited in `pcap` commit `5318ff6`:

```
# pcap slice -p tcp -r all.pcap -x all.index 192.168.0.51:53001 80.239.174.122:80
?ò?no packets found
```

Technically this output was correct since it was the proper output for an empty pcap file, but if we can make this more user-friendly through better error handling, great!

**Comment by philrz** [comment]
I've verified in `pcap` commit `4895043` that the symptom I was tracking has been addressed. No more "line noise". 😄 

```
# pcap slice -p tcp -r zq-sample-data.pcap -x zq-sample-data.idx -w 0.pcap 192.168.0.51:53001 80.239.174.122:80 
item does not exist: no packets found
```

Thanks @mattnibs!
