### ISSUE TITLE
driver doesn't handle reverse option

### ISSUE THREAD

**Issue by aswan** [brimsec/zq#599]
A reverse option is passed into here https://github.com/brimsec/zq/blob/master/driver/compile.go#L25 and then ignored.
It should be copied into the Reverse property of the proc.Context.

Looks like this was introduced in the process of refactoring the old duplicated code that turned into driver.  But ideally we should have zqd tests that would have caught this.

**Comment by philrz** [comment]
Note: This bug is currently responsible for the histogram being drawn incorrectly in the Brim app. For instance, a particular data set has a correct histogram that would look like this:

![image](https://user-images.githubusercontent.com/5934157/79577129-17634000-8079-11ea-8dbc-56f25396ec4a.png)

But in the presence of this bug, it looks like this:

![image](https://user-images.githubusercontent.com/5934157/79577160-234f0200-8079-11ea-8687-473cd4b14423.png)

**Comment by philrz** [comment]
Verified in Brim commit `b0c5f232` talking to `zqd` commit `a11a450`. The histogram looks correct again:

![image.png](https://images.zenhubusercontent.com/5e40bbae92d04e424a90e56f/309a922a-7359-4368-b180-b7b35a8a9e74)

Thanks @henridf!
