### ISSUE TITLE
boyer-moore design

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#681]
Document the design & tasks needed for https://github.com/brimsec/zq/issues/682 .

**Comment by nwt** [comment]
Here's how I see this going. Questions and suggestions are welcome!

1. Add these interfaces to package driver. (NewScanner has `filter ast.BooleanExpr` because we'll need it in step 6.
```go
// Scanner is the interface implemented by a record source that also provides
// statistics.
type Scanner interface {
	Pull() (zbuf.Batch, error)
	Stats() api.ScannerStats
}

// ScannerAble is the interface implemented by zbuf.Readers that provide an
// optimized implementation of the Scanner interface.  (Those that do not can be
// wrapped with scanner.NewScanner to provide the Scanner interface.)
type ScannerAble interface {
	NewScanner(ctx context.Context, filter ast.BooleanExpr, s nano.Span) Scanner
}
```

2. Make this change to driver.CompileWarningsChCustom.
```diff
 	filterAst, program := liftFilter(program)
-	scanner, err := newScanner(ctx, reader, filterAst, span)
-	if err != nil {
-		return nil, err
+	var scanner Scanner
+	if sa, ok := reader.(ScannerAble); ok {
+		var filter ast.BooleanExpr
+		if filterAst != nil {
+			filter = filterAst.Filter
+		}
+		scanner = sa.NewScanner(ctx, filter, span)
+	} else {
+		var err error
+		scanner, err = newScanner(ctx, reader, filterAst, span)
+		if err != nil {
+			return nil, err
+		}
 	}
```

3. Modify zngio.Reader to implement driver.ScannerAble.

4. Modify zngio.Reader to incorporate framing and compression from boom/common/tuple/{reader,writer}.go and boom/common/compression/lz4.go.  This has to live in harmony with the existing end-of-stream markers and zngio.Seeker. An alternative is the `<comp-type-code><comp-kind><uvarint-len><len bytes of compressed zng data>` approach from #521. I favor the first approach primarily because I have a better feeling for how it will look (owing to familiarity with the boom implementation), but if I'm open to the second approach if anyone prefers it.

5. Modify zio/zngio.Reader to incorporate buffer management from boom/common/tuple/{buffer,chunk}.go.

6. Implement a simple string-search pre-filter in zngio.Reader using bytes.Contains. This involves some analysis of NewScanner's `filter ast.BooleanExpr` argument to decide whether we should do a string search and, if so, exactly what it should look like. For example, values that might appear in either binary or string form (i.e, values of float, int, ip, net, and port type) will require two searches; we'll have to evaluate whether that's worth doing.

7. Replace bytes.Contains with the stringFinder from https://github.com/golang/go/blob/master/src/strings/search.go, which implements Boyer-Moore string search.

**Comment by henridf** [comment]
👍 :shipit: !

As to the question 4, I don't have any technical rationale for one or the other, so I'd say go with what's quickest to produce, which sounds like the first approach.

**Comment by alfred-landrum** [comment]
Regarding step 4: If we don't use a type code / control message, we'll need to introduce a new framing header & scheme, right? That will need to align to record boundaries & end-of-stream markers just like the control message approach would, but it will be more complex to implement, since the coupling has to be expressed across abstraction boundaries.

**Comment by mattnibs** [comment]
Nice. So would zngio.Reader.Read will call zngio.Reader.Pull under the covers? If so, I assume that zngio.Reader.Read would have to copy each new record is that right?

**Comment by nwt** [comment]
> Regarding step 4: If we don't use a type code / control message, we'll need to introduce a new framing header & scheme, right? That will need to align to record boundaries & end-of-stream markers just like the control message approach would, but it will be more complex to implement, since the coupling has to be expressed across abstraction boundaries.

@alfred-landrum and I discussed this and agreed on the the control message approach.

**Comment by nwt** [comment]
> Nice. So would zngio.Reader.Read will call zngio.Reader.Pull under the covers? If so, I assume that zngio.Reader.Read would have to copy each new record is that right?

@mattnibs: Read will call Pull, but it needn't copy the bytes since it can return volatile records.

**Comment by nwt** [comment]
I forgot to mention that I'm planning to stick with LZ4 compression since it has a good balance among compression ratio, compression speed, and decompression speed (per https://github.com/inikep/lzbench#benchmarks).
