### ISSUE TITLE
More helpful ndjsonio parsing errors

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#760]
@philrz ran into an issue with typed ndjson where a field that was declared as `uint64` in types.json, but appeared in a json record with a non-integer value of `1.521835102647908E12`. 

This failed with a quasi-hostile error message of `line 1: bad format`. This needs to be better.

**Comment by henridf** [comment]
(This "bad format" error messages is used throughout the readers in zio, but typed ndjson is the one where this is most likely to be visible, and an issue).

**Comment by philrz** [comment]
Verified in `zq` commit `753d8a6`.

The example as originally stated is actually not reproducible anymore because thanks to #766 we now support these integer values when they appear in NDJSON in scientific notation.

```
$ cat types.json 
{
  "descriptors": {
    "dns_log": [
      {
        "name": "_path",
        "type": "string"
      },
      {
        "name": "datetime",
        "type": "int64"
      }
    ]
  },
  "rules": [
    {
      "descriptor": "dns_log",
      "name": "_path",
      "value": "dns"
    }
  ]
}

$ cat sci-not.ndjson 
{"_path":"dns","datetime":1.521835102647908E12}

$ zq -t -j types.json sci-not.ndjson 
#0:record[_path:string,datetime:int64]
0:[dns;1521835102647;]
```

However, as is shown in the tests in the linked PR, we now have a more helpful error message than we did before when the conversion is otherwise not possible.

```
$ cat stringy.ndjson 
{"_path":"dns","datetime":"foo"}

$ zq -t -i ndjson -j types.json stringy.ndjson 
stringy.ndjson: line 1: field "datetime" (type int64): strconv.ParseFloat: parsing "foo": invalid syntax
```

Thanks @henridf!
```
