### ISSUE TITLE
Type casting with put

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zq#786]
We'd like a way to use the `put` processor to set a field's value and its type.

This issue started out as a mission to just prototype this by covering only two ZNG types: `time`, and `ip`, with extra handling is needed for time, since we need to both update the bytes of the record and the `TS` field of the Record struct. However, we ended up with a broad implementation.

**Comment by philrz** [comment]
Verified in `zq` commit `753d8a6`.

Here's the classic of JSON having to treat an IP address as a string:

```
$ echo '{"source": "192.168.0.51"}' | zq -t -
#0:record[source:string]
0:[192.168.0.51;]
```

With the benefit of the new functionality, we can make a new field that holds the properly-typed value:

```
$ echo '{"source": "192.168.0.51"}' | zq -t 'put src=source:ip' -
#0:record[source:string,src:ip]
0:[192.168.0.51;192.168.0.51;]
```

...or we can overwrite the existing named field with the properly-typed value:

```
$ echo '{"source": "192.168.0.51"}' | zq -t 'put source=source:ip' -
#0:record[source:ip]
0:[192.168.0.51;]
```

In either case, the correct typing means we can do stuff like CIDR matches.

```
$ echo '{"source": "192.168.0.51"}' | zq -t 'put source=source:ip | filter source =~ 192.168.0.0/16' -
#0:record[source:ip]
0:[192.168.0.51;]
```

For time values, let's say we'd been storing timestamps as milliseconds since epoch. Like in other languages, note that float vs. integers matters, so we'll use both.

```
$ cat mil.zng 
#0:record[millint:uint64,millfloat:float64]
0:[1425565514419;1425565514419;]
```

Since our time values in Zeek/ZNG/Brim are often presented/input as seconds since epoch, let's do math for this conversion at the same we cast to the correct type.

```
$ zq -t "put ts1=(millint/1000):time,ts2=(millfloat/1000):time,ts3=(millint/1000.0):time" mil.zng 
#0:record[millint:uint64,millfloat:float64,ts1:time,ts2:time,ts3:time]
0:[1425565514419;1425565514419;1425565514;1425565514.41899991;1425565514.41899991;]
```

Note how `ts1` is a whole number, since we're doing math on two integer values, but `ts2` and `ts3` came out with sub-second precision since there was at least one float involved in the math.

In any case, when this ZNG is imported into Brim, the timestamped are rendered as human-readable times.

![image](https://user-images.githubusercontent.com/5934157/82003474-4c7d9680-9615-11ea-83bf-b263da382348.png)

Thanks @aswan!
