### ISSUE TITLE
Unclear error message in response to bad addr

### ISSUE THREAD

**Issue by philrz** [brimsec/zq#927]
Repro is with `zq` commit `ee18903`.

If I make a typo in an IP address:

```
$ zq -t "id.resp_h=10.150.0.999" *
bad addr value field [49 48 46 49 53 48 46 48 46 57 57 57]
```

**Comment by marktwallace** [comment]
Notes:
To repro this, I used sample data from conn.log. For commit ee18903 I got the same error as above:

$ zq -t "id.resp_h=10.150.0.999" conn.log
bad addr value field [49 48 46 49 53 48 46 48 46 57 57 57]

In the branch I pulled from master to fix it, I get:

$ zq -t "id.resp_h=10.150.0.999" cmd/zq/conn.log
bad addr value field [49 48 46 49 53 48 46 48 46 57 57 57]

So the bug is still there, and I will go find it now.

**Comment by philrz** [comment]
Verified in `zq` commit `04f2c11`. The error message is significantly improved:

```
$ zq -t "id.resp_h=10.150.0.999" *
net.ParseIP: parsing "10.150.0.999": syntax error
```

This also led me to think more about the nature of such error messages, and I said more about this in [a late PR comment](https://github.com/brimsec/zq/pull/1106#discussion_r473137566). However, we've definitely addressed the tactical issue at hand.

Thanks @marktwallace!
