### ISSUE TITLE
all.bzng to all.zng migration

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#952]
`zqd` has code that checks for a `all.bzng` code if `all.zng` isn't found (https://github.com/brimsec/zq/blob/master/zqd/storage/filestore/filestore.go#L77).

Per @alfred-landrum if we want to remove it, we should replace it with a migration like so:

> We can increase the `configVersion` in package space to 2, and inside NewManager, add a check for bzng & rename the file. I"m guessing there are few if any bzng files out there, but we now have a place for data/config migrations, so we do that whenever we can.

**Comment by philrz** [comment]
@alfred-landrum: I know you're in the middle of ZNG migrations as part of #1376. I'm guessing there's not many `all.bzng` files still lying around out there and I guess it qualifies as scope creep, but since that's already going through the trouble of recognizing an older format and doing a migration, would you want to expand #1376 to include this so we can check it off the list?

**Comment by alfred-landrum** [comment]
This is handled during the alpha zng migration:
https://github.com/brimsec/zq/issues/1376

as part of the alpha zng migration, any remaining all.bzng files are renamed to all.zng (and converted from alpha to beta zng).

**Comment by philrz** [comment]
I took a shot at verifying this and was pleased with what I found. I went all the way back to Brim `v0.6.0`, which was quite a trip down memory lane since it was still back in the days when importing a pcap meant a `.brim` directory was created adjacent to the pcap file in its original location. So after the import, things looked like:

```
~/pcap/wrccdc.pcap.brim$ ls -al
total 68432
drwxr-xr-x   5 phil  staff       160 Dec  9 11:56 .
drwxr-xr-x  19 phil  staff       608 Dec  9 11:55 ..
-rw-r--r--   1 phil  staff  33804239 Dec  9 11:56 all.bzng
-rw-r--r--   1 phil  staff        92 Dec  9 11:55 info.json
-rw-r--r--   1 phil  staff    424801 Dec  9 11:55 packets.idx.json
```

I then upgraded to Brim `v0.20.0` and both the alpha migration and rename were successful, extracting pcap slices still worked, etc. The "after":

```
~/pcap/wrccdc.pcap.brim$ ls -al
total 37760
drwxr-xr-x   5 phil  staff       160 Dec  9 11:57 .
drwxr-xr-x  19 phil  staff       608 Dec  9 11:55 ..
-rw-rw-rw-   1 phil  staff  18306992 Dec  9 11:57 all.zng
-rw-------   1 phil  staff       114 Dec  9 11:57 info.json
-rw-r--r--   1 phil  staff    424939 Dec  9 11:57 pcap.json
```
